In [1]:
import numpy as np
print(np.version.version)

1.13.3


In [2]:
lst1 =[1,2,3]
lst2 =[]

In [3]:
from numpy import random

In [4]:
from numpy import random
random.randint(0,100,size=(10,2))

array([[ 1, 18],
       [38, 73],
       [38, 12],
       [58, 33],
       [14, 69],
       [11, 52],
       [73, 32],
       [23, 34],
       [83, 49],
       [23, 24]])

In [5]:
random.rand(3,4)

array([[ 0.84488058,  0.578195  ,  0.22360802,  0.35994734],
       [ 0.74149828,  0.88349224,  0.54549158,  0.54674222],
       [ 0.52310004,  0.53465061,  0.34445705,  0.5537732 ]])

In [6]:
####Generating standard Arays:array with o and 1

In [7]:
#RG -single dimension array
import numpy as np
n1=np.array([10,20,30,40,50])
n1

array([10, 20, 30, 40, 50])

In [8]:
n2=np.array([[10,20,30,40,50],[60,70,80,90]])
n2

array([list([10, 20, 30, 40, 50]), list([60, 70, 80, 90])], dtype=object)

In [9]:
type(n2)  #n-dimensional array

numpy.ndarray

In [10]:
np.zeros((1,3))  # numpy array with 1 row and 3 columns hanving zero value

array([[ 0.,  0.,  0.]])

In [11]:
a=np.zeros((3,5))
a

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [12]:
b=np.ones((3,4))
b


array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [13]:
f=np.full((2,2),100)
f

array([[100, 100],
       [100, 100]])

In [14]:
store=np.arange(10,90,5)  # arange(start, exclusive end, step)
store

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85])

In [15]:
np.random.randint(500,600,5) # start, end, size

array([575, 559, 543, 519, 560])

In [16]:
n2

array([list([10, 20, 30, 40, 50]), list([60, 70, 80, 90])], dtype=object)

In [17]:
n2.shape

(2,)

In [18]:
n3=np.array([[1,2,3],[4,5,6]]) #creating 2-d array
type(n3)
n3

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
n3

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
n3.shape

(2, 3)

In [21]:
n3.shape=(3,2) #changing the shape of the array
n3

array([[1, 2],
       [3, 4],
       [5, 6]])

In [22]:
#joining NumPy Arrays
n5=np.array([10,20,30])
n6=np.array([40,50,60])
np.vstack((n5,n6))

array([[10, 20, 30],
       [40, 50, 60]])

In [23]:
np.hstack((n5,n6)) #horizontal stacking of 2 single dimension arrays


array([10, 20, 30, 40, 50, 60])

In [24]:
np.column_stack((n5,n6))


array([[10, 40],
       [20, 50],
       [30, 60]])

In [25]:
np.column_stack((n5,n6)).shape

(3, 2)

In [26]:
#Numpy intersection and difference
n1=np.array([10,20,30,40,50,60])
n2=np.array([50,60,70,80,90])
np.intersect1d(n1,n2)

array([50, 60])

In [27]:
np.setdiff1d(n1,n2)

array([10, 20, 30, 40])

In [28]:
np.setdiff1d(n2,n1)

array([70, 80, 90])