In [1]:
import numpy as np
np.version.version

'1.13.3'

In [2]:
import numpy as np
a=[5,9,12]
np.array(a)

array([ 5,  9, 12])

In [3]:
np.array([10,13,17])

array([10, 13, 17])

In [11]:

import numpy as np
np.arange(0,20,1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [12]:
np.linspace(1,15,7)

array([  1.        ,   3.33333333,   5.66666667,   8.        ,
        10.33333333,  12.66666667,  15.        ])

In [ ]:
####2d Numpy arrays


In [ ]:
a=np.arange(0,36,1)

In [13]:
a

[5, 9, 12]

In [15]:
a.reshape(3,2,2,3)

AttributeError: 'list' object has no attribute 'reshape'

In [ ]:
indexing array

In [ ]:
a=[2,3,5,6]
